services:
  postgres:
    image: postgres:16-alpine
    container_name: task_gov_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root_password_secure
      POSTGRES_DB: task_gov_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network

volumes:
  postgres_data:

networks:
  task_network: